[package]
name = "app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.26.2"
bible_file_format = { path = "../bible_file_format" }
markdown = "1.0.0-alpha.16"
